### ISSUE TITLE
seek performance?

### ISSUE THREAD

**Issue by vxhviet** [protyposis/ITEC-MediaPlayer#15]
Hi @protyposis, I have a question regarding the seek performance of this library. Basically, what I'm trying to do is implement a scrubbing feature [like this](https://www.youtube.com/watch?v=083iy30lbio&feature=youtu.be&t=1m21s) on local video file.

I've tried a bunch of player before but the best one up until now is ExoPlayer; accurate seeking, ok performance for video up to 720p, for higher resolution, the performance is quite bad. I understand it need to take time to decode frame from the key frame but I hope somehow this library can deliver the impossible :dancer: 

Sorry I'm currently away from my working machine so I can only play with your demo app.

**Comment by protyposis** [comment]
Hi, I'm afraid this library can't deliver the impossible ;)

For a correct picture, all frames beginning with the previous I/sync/key frame need to be decoded, and since ExoPlayer and this library are both using Android's MediaCodec for decoding, the performance should be the same.

The ITEC-MediaPlayer has a seek mode called FAST_EXACT where only the first sync frame and the target frame are decoded and all frames in between are skipped. This inevitably leads to decoding errors / block artefacts, but depending on the video content and GOP size it might be useable in some cases.

**Comment by HBiSoft** [comment]
@vxhviet did you get this working? If you did, can you please share? I'm currently trying to achieve this with mediacodec/mediaextractor and a SurfaceTexture, is that what you ended up doing?

**Comment by vxhviet** [comment]
Yes I ended up using `MediaCodec`. If you don't have a very strict requirement for performance, you could try using `FFmpeg` though. `FFmpeg` are a lot more complicated but it can support api < 18.

Note that I'm talking about `FFmpeg` using as a run time (using NDK to input frame) not the general pre-built `FFmpeg` that's very common but the performance is too poor for these kind of application. Took me a while to realize this.

**Comment by HBiSoft** [comment]
@vxhviet Thank you for your reply. I don't want to be bothersome, but can you please look at what I have implemented so far, I uploaded it to [gist.github](https://gist.github.com/HBiSoft/5c9c5a2ff5f8446f6a8f65ebe7df65fa) and I have commented below what issue I'm currently having. Thank you once again for taking the time to reply.
