### ISSUE TITLE
[VideoView] play audio delayed after seek

### ISSUE THREAD

**Issue by ghost** [protyposis/ITEC-MediaPlayer#20]
When I seek videoview and re-play, the videoview only rendered image and after about 400ms, audio was actually played. 
I have set the seekMode to Fast. Any fix?

**Comment by protyposis** [comment]
Does it only happen when seekMode is set to fast? Does it happen in the demo app too? Please tell me the exact steps to reproduce the problem.

**Comment by ghost** [comment]
Sorry for my late reply, i will build your demo app and let you know as long as possible.

**Comment by ghost** [comment]
Here is my scenario:
1. I pulled your full source code, run in android studio newest version
2. I opened up your videoview and try to seek, the audio work quite well and it just small delay(about 50ms), so I completely accept it.
3. I changed your code in the VideoViewActivity, set videoview.setSeekmode(FAST).
4. After that, I realized that, at the first seek audio still work, but the second or more seek make the audio of videoview delayed.

Should I upload my video?
![untitled](https://cloud.githubusercontent.com/assets/13575382/17124830/279492c2-5318-11e6-9483-8deb3f556157.png)

**Comment by ghost** [comment]
I tested this issue on (Motorola X 2014, android 6.0, arm-v7) and (Asus zenpad 3, android 5.1, x86)

**Comment by protyposis** [comment]
Thanks, I'm looking into it. I can observe it on my test videos too so you don't need to upload yours.

**Comment by protyposis** [comment]
This is actually not a bug but expected behavior. Fast seek seeks to a sync frame, and since audio frames do not necessarily have to follow directly after a sync frame, it can take some time until the next audio frame is read and audio playback continues. If this is a problem, please choose another seek mode as a workaround. I'll push an update in the coming days with different fast seek options which will provide a solution to this problem.

**Comment by ghost** [comment]
So FastSeek means fast seeking video frame, not apply to audio stream. Therefore, video frame have to wait to sync audio stream, right?
Thanks, I'm waiting your update.

**Comment by protyposis** [comment]
Version 3.1.0 is now available and adds additional fast seek modes. Like I said, this problem is technically not a bug and this behavior depends on file encoding and multiplexing settings. I noticed however that the two new alternative seek modes `FAST_TO_CLOSEST_SYNC` and especially `FAST_TO_NEXT_SYNC` mitigate this behavior a lot. Let me know if it works for you!

**Comment by ghost** [comment]
WOW it worked perfectly, thank you so much!
