### ISSUE TITLE
play back speed audio bug

### ISSUE THREAD

**Issue by chanbbong** [protyposis/ITEC-MediaPlayer#24]
[MediaPlayer-Extended's 2x]

[mediaplayer-extended.m4a.zip](https://github.com/protyposis/MediaPlayer-Extended/files/431880/mediaplayer-extended.m4a.zip)

[Youtube's 2x]

[youtube.m4a.zip](https://github.com/protyposis/MediaPlayer-Extended/files/431881/youtube.m4a.zip)

same video's play back speed but different audio

**Comment by protyposis** [comment]
This is expected behavior. MP-X uses [AudioTrack.setPlaybackRate](https://developer.android.com/reference/android/media/AudioTrack.html#setPlaybackRate%28int%29) to change the playback speed, which is basically the same as resampling and affects the audio pitch. YouTube uses a dedicated time stretching algorithm to preserve the pitch.

**Comment by nzala** [comment]
ca u use[https://github.com/waywardgeek/sonic]( https://github.com/waywardgeek/sonic)

**Comment by nzala** [comment]
[https://github.com/google/ExoPlayer/issues/26#issuecomment-164022902](https://github.com/google/ExoPlayer/issues/26#issuecomment-164022902)
