### ISSUE TITLE
Memory Leak in Audio Buffer?

### ISSUE THREAD

**Issue by selalipop** [protyposis/ITEC-MediaPlayer#25]
I have an app that plays different videos in a loop and noticed a slow memory leak. Replacing my usage of this VideoView with the built in VideoView on Android 4.4 seems to have gotten rid of the leak.

I dumped memory and noticed that there was a steady increase in the number of byte[] instances being allocated somewhere. Most of these byte arrays are exactly 4096 bytes long with this stacktrace (in the form `fieldName : class => parentObject`) :

```
byte[4096] => 
backingArray : java.nio.ByteArrayBuffer =>
buffer : net.protyposis.android.mediaplayer.AudioPlayback$BufferQueue$Item =>
(buffer is an element of array of type java.lang.Object[12])
array : java.util.ArrayList =>
emptyBuffers : net.protyposis.android.mediaplayer.AudioPlayback$BufferQueue =>
mBufferQueue : net.protyposis.android.mediaplayer.AudioPlayback
```

The native VideoView doesn't seem to be creating these objects using the same series of calls I was making to the MediaPlayer-Extended VideoView, and the leak is gone. Is there a method I should be calling to get rid of those buffer objects, or is this a leak?

**Comment by protyposis** [comment]
Thanks for reporting, unfortunately I cannot reproduce the issue on Android 4.4 and 7.0. When I repeatedly load videos into the same ViewView, memory consumption grows a tiny bit because of these buffers and the time it takes the garbage collector to remove them. Ultimately, they do not seem to leak though and the overhead is just a few megabytes (and does not change much if I explicitely remove the buffers).

Can you give me more details on your issue? How long are the videos in your loop, or how frequently do you load them? How much memory do you think is leaking?

Btw., the native VideoView works very differently so you cannot compare the call stacks or data structures they use.

**Comment by selalipop** [comment]
Sorry, you're absolutely right, the buffers weren't leaking, the GC was just taking a while to collect them, adding explicit GC calls exposed a leak related to work I was doing with a 3rd party library in the prepare callback. The videos I was playing were 1 second long which was exacerbating the issue.

Thanks so much for looking into this, and sorry again for my misunderstanding here, this library is really saving me form a lot of headaches with the built in VideoView on the device I'm working with.

**Comment by protyposis** [comment]
Thanks, I'm glad you found the issue and that the library is of help!

**Comment by jerrywoodz** [comment]
My app uses VideoView to play 25 of video files with duration between 15 seconds and 32 seconds in a loop in a media box with Android 4.4.2, the app stops to play video file after 15 hours, then, I can see no onPrepared() is happened after execute set videoURI() or something wrong in Media player every time.
If my app plays 10 of video files with duration around 30 minutes in a loop in same media box, then ,the app stops to play video after three days
Is it Media player bug in Android 4.4.2?
