### ISSUE TITLE
MEDIA_INFO_BUFFERING_START question

### ISSUE THREAD

**Issue by aleksandra-majchrzak** [protyposis/ITEC-MediaPlayer#30]
I'm trying to handle situation in which user seeks to video time that hasn't been buffered yet. I expect that MediaPlayer will call onInfo() with MEDIA_INFO_BUFFERING_START message (this happens with standard MediaPlayer). However, it doesn't. I would like to show a  progress dialog in time between seek click and start of video playback (it sometimes is even few seconds, so I cannot leave it without any info). How should I handle it properly? Are there any other listeners that react on video being buffered?

**Comment by protyposis** [comment]
Thanks, that will be fixed in the next version.

In the meantime, use the `OnSeekListener` to show the progress dialog and the `OnSeekCompleteListener` to hide it. If the seek takes a long time, either because you're using exact seek mode or because of buffering, then the dialog will be visible. If a seek is quick, the dialog will be gone before the user realizes it.
