### ISSUE TITLE
Accept custom OkHttpClient instances

### ISSUE THREAD

**Issue by Guichaguri** [protyposis/ITEC-MediaPlayer#31]
It would be useful in case you want to use cache or set other options.

**Comment by protyposis** [comment]
Can you elaborate a bit? What would be concrete use cases?

**Comment by Guichaguri** [comment]
In [DashMediaExtractor](https://github.com/protyposis/MediaPlayer-Extended/blob/master/MediaPlayer-DASH/src/main/java/net/protyposis/android/mediaplayer/dash/DashMediaExtractor.java#L92), an OkHttpClient is initialized. It would be useful if it accepted another instance.

It can be useful for configuring cache, proxy, authenticators, read/write timeouts, cookie management, etc

``` java
// HTTP Client with cache and cookie management
OkHttpClient client = new OkHttpClient.Builder()
    .cache(new Cache(new File(context.getCacheDir(), "media"), 10 * 1024 * 1024))
    .cookieJar(new JavaNetCookieJar(new CookieManager()))
    .build();
```

EDIT: I see you have your own caching code, how does it work? Is it better than using OkHttp's cache?

**Comment by protyposis** [comment]
It's hard to say if my caching code is better, but it's different and probably has advantages and disadvantages:
- DashMediaExtractor caches processed segments, OkHttp caches unprocessed HTTP responses. A processed segment is a segment merged with the init segment and converted to an unfragmented MP4 (in case of fragmented MP4) that the MediaCodec can decode. OkHttp caches the unprocessed parts, so the DashMediaExtractor saves processing overhead when a segment is taken from the cache.
- DashMediaExtractor always caches segments, OkHttp works according to the cache configuration headers from the server. So a server can prevent OkHttp from caching, which might or might not be desirable.
- The cache size in DashMediaExtractor is currently hardcoded to 100 megabytes. That needs to be made configurable.
- DashMediaExtractor's cache deletes cached files after playback when the extractor instance is released to not unnecessarily waste storage space. This might also not always be desirable, e.g. if playback of the same video is repeated with a new instance. I don't know how this is handled in OkHttp.
- Some DASH setups use range requests to request segments from a single file instead of separate files per segment. OkHttp does not cache range requests, so in this case caching is technically disabled. DashMediaExtractor caches such segments sourced from range requests.

I think there might be cases where it makes sense to use HTTP caching additionally to or instead of (by setting cache size to zero) DashMediaExtractor's cache. Also setting up proxies, cookies, etc. seem like valid uses cases to me so I'll add that in the next version.

**Comment by Guichaguri** [comment]
Thank you!
