### ISSUE TITLE
I can't increase speed more then two times

### ISSUE THREAD

**Issue by kotya341** [protyposis/ITEC-MediaPlayer#4]
I have to create x8 speed logic in my video view 
but when I set value more then 2
such as x4 videoView.setPlaybackSpeed(4.0f);
I still have only x2 speed increasing

**Comment by protyposis** [comment]
Hi, unfortunately this is expected behavior, you can only speed up as much as the decoder can process... so the speedup factor is limited by the hardware power.

Higher speedup factors could only be achieved by skipping decoding of certain frames, which will most probably result in block artifacts. Also, the Android API does not expose the type of frame without decoding it, so it can happen that sync frames get skipped. The solution I can think of would be to write a custom parser and logic to skip decoding certain frames without compromising the picture quality too much... which would be a lot of work.

**Comment by protyposis** [comment]
Since v2.2.0, the media player is optimized for better performance, which enabled higher playback speeds. It still has to decode all frames, so the hardware performance is still a limiting factor.
