### ISSUE TITLE
setPlaybackSpeed(float) param range

### ISSUE THREAD

**Issue by KyleCe** [protyposis/ITEC-MediaPlayer#64]
(Actually, I want to set a more wide range of speed to the playback, can you help me?)

// comment in the source code
  /**
   * Set video and audio playback speed
   *
   * @param speed e.g. 0.8 or 2.0, default to 1.0, range in [0.5-2]
   */
  public native void setPlaybackSpeed(float speed);

"Sets the playback speed factor (e.g. 1.0 is normal speed, 0.5 is half speed, 2.0 is double speed). Audio pitch changes with the speed factor."

why limit the range?

I appreciate any answer

**Comment by protyposis** [comment]
~~I limited it to 2x speed because none of my tested mid-range phones were able to decode 3x speed. If I would allow arbitrary speeds, people would open issues and ask why it doesn't playback with 10x speed, so this is a more or less artificial limitation I unfortunately had to introduce.~~ Not true, playback speed is not limited. I was confused by the comment posted above, which comes from another media player library.

Allowing much higher playback speeds would require dropping frames and not decoding them at all, which is not possible with the `MediaExtractor`/`MediaCodec` API. See #4.

**Comment by mike20139631** [comment]
Thank you for create this mediaplayer,it's useful for me.
at the same time,according to your commend,(i have seen #4) is there any method to  setvideospeed at 4.0f let phone run on maybe 3x and android won't crash?
because,i run app(setspeed 4.0，setlooping is true) at samgsung note3(android 5) was fine,but when i run same app at machine(android 4.2) ,it can only replay twice.it'll crash through to third times.
any answer will be helpful. thanks.

**Comment by protyposis** [comment]
I just looked into the sources and saw that I never limited playback speed in the library. It is only limited in the demo app.

You can set whatever speed you like, but it won't playback faster than the device can process. That means, you're free to set playback speed to 100x, but it will still only play back at 2x or 3x or 4x or whatever is possible on the device.
