### ISSUE TITLE
onBufferingUpdate(MediaPlayer mp, int percent) always 100%

### ISSUE THREAD

**Issue by IHiroXI** [protyposis/ITEC-MediaPlayer#88]
onBufferingUpdate(MediaPlayer mp, int percent)
always returning 100 percent with http stream or does not return at all, its ok?
how i can take buffering position for seekTo() use?
getBufferPercentage() returned 2147483647

**Comment by protyposis** [comment]
There is a bug in the buffer percentage calculation introduced in 4.3.3 (`getInputSamplePTS()` is used for buffer calculation even when it returns `PTS_UNKNOWN`/`-1`). Will be fixed in the next release.

I have no idea how you see the buffer position connected to `seekTo`. Anyway, it's not related to the percentage calculation bug so please open a new issue with a better description.

**Comment by IHiroXI** [comment]
thanks for fix.

im using seekTo with seekBar for seeking on the track. if im listening from sdcard then full track available always, but if listening from http stream i have no way to know how many are currently loaded.

**Comment by protyposis** [comment]
Fix has been released with v4.4.0
